### ISSUE TITLE
Test failure (res.toError() should return an Error)

### ISSUE THREAD

**Issue by chrisbartley** [kmalakoff/superagent-ls#2]
When doing a `make test`, one of the tests is failing (I'm using Node.js 0.12.7):

```
1) res.toError() should return an Error:
     Uncaught AssertionError: err.status == 400
      at /Users/chris/Downloads/superagent-ls-1.3.0/test/node/toError.js:20:7
      at Request.callback (/Users/chris/Downloads/superagent-ls-1.3.0/lib/node/index.js:785:12)
      at Stream.<anonymous> (/Users/chris/Downloads/superagent-ls-1.3.0/lib/node/index.js:990:12)
      at Stream.emit (events.js:129:20)
      at Unzip.<anonymous> (/Users/chris/Downloads/superagent-ls-1.3.0/lib/node/utils.js:108:12)
      at Unzip.emit (events.js:129:20)
      at _stream_readable.js:908:16
      at process._tickCallback (node.js:355:11)
```

FWIW, it fails for visionmedia's original superagent, too.  I can file there instead if you'd rather limit the number of differences in your fork.

**Comment by kmalakoff** [comment]
@chrisbartley absolutely file it there. I'm trying to limit the changes in this fork and so it is probably better like you suggest to go to the source of the problem.

**Comment by chrisbartley** [comment]
Submitted: https://github.com/visionmedia/superagent/issues/790
